$ = jQuery  = require('jquery')
flot        = require('flot')
moment      = require('moment')
momenttz    = require('moment-timezone')
Handlebars  = require('handlebars')
URI         = require('urijs')
ss          = require('simple-statistics')
bootbox     = require('bootbox')
Color       = require('color')
Holder      = require('holderjs')
marked      = require('marked')
hljs        = require('highlight.js')
Mousetrap   = require('mousetrap')
bean        = require('bean')
bootstrap   = require('bootstrap')
select2     = require('select2')
store       = require('store')
growl       = require('bootstrap-notify')
datatables  = require('datatables')(window, $)
saveAs      = require('file-saver').saveAs
Promise     = require('bluebird')
humanize_duration = require('humanize-duration')

